spring.application.name=login-system
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DBURL}
spring.datasource.username=${DBUSER}
spring.datasource.password=${DBPASSWORD}

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=validate

api.security.token.secret=${JWTSECRET}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAILFROM}
spring.mail.password=${EMAILPASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
