spring.application.name=login-system
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DBURL}
spring.datasource.username=${DBUSER}
spring.datasource.password=${DBPASSWORD}

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl.auto=validate

api.security.token.secret=${JWTSECRET}
